FROM node:16 as builder

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json ./

RUN npm i

COPY . .

RUN npm run build

FROM node:16-alpine

RUN apk update && \ 
    apk add git && \
    apk add --update tzdata

# Change TimeZone
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install --only=production

COPY --from=builder /usr/src/app/prisma ./prisma
COPY --from=builder /usr/src/app/dist ./dist

RUN npm run generate

CMD [ "node", "dist/index.js" ]