FROM node:16-slim

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json ./

RUN npm install

COPY . .

RUN npm run build


COPY --from=builder /usr/src/app/dist ./dist

CMD [ "node", "dist/index.js" ]